---
- name: Configurar IPv6 en Loopback33
  hosts: cisco
  gather_facts: no

  tasks:
    - name: Configura dirección IPv6 global
      ios_config:
        lines:
          - interface Loopback33
          - ipv6 address 3001:ABCD:ABCD:1::1/128
          - ipv6 address FE80::1 link-local

